const quotes = [
"A bug is just a misunderstood feature.",
"When you aim for the stars, you most definitely won’t reach them, but you will have a great time on your fall until you smack on the ground and DIE",
"Just push it to main and see what happens.",
"Why do we need comments when the code is self-explanatory?",
"I love pinterest.",
"I dont even understand my code sometimes.",
"I wont question where the code is from if it works",
"I love Animal Crossing",
"If theres a quizlet, theres an Excellence",
"The calculator said 2+2=5 so who am I to argue?",
"I want to cheese.",
"I dont sleep much thats crazy howd you know that",
"Push to prod, it works on my machine.",
"Figma is life.",
"Sometimes headache. Sometimes tired. Sometimes both. Always slitro.",
"I am not foxboy that is someone else.",
"This is why I use a mac",
"This code works because I believe in magic.",
"Why would I test it? I wrote it.",
"Hey chatGPT why is my arduino smoking",
"If you ask me to write this website in react, i will react violently.",
"somebody stole my car radio",
"somebody stole my code and put it on github.",
"who needs documentation when you have no documentation?",
"hey chatGPT why is my mac becoming a space heater",
"just because it works doesnt mean its right.",
"Im not procrastinating, Im doing side quests.",
"when in doubt, just remove some comments.",
"AAAAAAH JAVASCRIPT AAAAAAH",
"Code never lies, comments sometimes do.",
"To understand what recursion is, you must first understand recursion.",
"I will repeat myself again, i am not foxboy.",
"Why would I use windows when I can use macOS",
"Congratulations, you found an easter egg!",
"Who needs semicolons anyway",
"Hack Club is life.",
"Hack Club made me learn CSS.",
"haha windows breaks localhost haha",
"There is no bug in the code because I SAID SO.",
"This site is more than slightly broken on mobile.",
"Guess what? I dont test on mobile.",
"Who is foxboy anyway and why am I being mistaken for him?",
"Why write code when you can just code?",
"I have pycharm installed but I dont know how to write python.",
"Why would I use linux when I can use macOS",
"I am going insane",
"Javascript is horrible",
"Python is horrible",
"Java is horrible",
"Ruby is horrible",
"C++ is horrible",
"HTML is horrible",
"CSS is horrible",
"You must be insane to use Chrome",
"my code works on my machine",
"Also check out codingcorner.dev!",
"i like neovim",
"i dont like emacs",
"i use VSCode",
"Chrome is horrible",
"Safari is a browser",
"Brave is a close second last",
"Edge is just chrome with a different logo",
"Firefox is okay i guess",
"i use macOS because i use macOS",
"aeeeaaaeeeeehhhhhhhhhh",
"why is everyone obsessed with dark mode",
"i use dark mode because light mode gives me headaches",
"i hate samsung tizen.",
"i use an apple tv.",
"panic on the brain, world has gone insane",
"i want to cheese",
"sleep is for the weak",
"I love hack club",
"Check out codingcorner.dev",
"mery chrimus",
"hapy knee year",
"eat your vegetables",
"what even happens in canberra",
"why is the sky blue",
"why is water wet",
"we all ponder of something great",
];

function showRandomQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  document.getElementById("clickMe").textContent = quotes[randomIndex];
}
